### ISSUE TITLE
Inquiry about Dataset, and Compatibility with SDN

### ISSUE THREAD

**Issue by kingxiaofire** [GANGISHETTIPRANAY/sdn_intrusion_analysis_using_ml_and_dl.ipynb#1]
I am interested in the project and would like to gather more information regarding the following aspects:

Could you please specify the dataset used in this work and provide information on where it can be downloaded from?
Has there been any related research paper published for this work? If yes, could you share the details or provide a reference to the publication?
I am curious to know if this project is capable of running in Software-Defined Networking (SDN) environments. Could you clarify if the system is designed to be compatible with SDN setups?

Your insights on these points would greatly assist in understanding the project better. Thank you for your attention to these inquiries.

**Comment by GANGISHETTIPRANAY** [comment]
Thank you for your interest in the project. I am happy to provide more information on the points you've raised.

I have made the necessary updates to my repository, where you can now find all the relevant details, including the dataset used and the associated research paper. Please feel free to review the updated information at your convenience.
